// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

/**
 * @title Groth16 Verifier Contract (auto-generated by SnarkJS)
 * @dev Used for verifying zkSNARK proofs generated from Circom circuits.
 */

library Pairing {
    struct G1Point {
        uint X;
        uint Y;
    }

    struct G2Point {
        uint[2] X;
        uint[2] Y;
    }

    // Returns the generator of G1
    function P1() internal pure returns (G1Point memory) {
        return G1Point(1, 2);
    }

    // Returns the generator of G2
    function P2() internal pure returns (G2Point memory) {
        return G2Point(
            [11559732032986387107991004021392285783925812861821192530917403151452391805634,
             4082367875863433681332203403145435568316851327593401208105741076214120093531],
            [8501145338530734403076486052345081349246662438305095956959819839611622805163,
             10857046999023057135944570762232829481370756359578518086990519993285655852781]
        );
    }

    // Negate a point
    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, q_mod() - (p.Y % q_mod()));
    }

    // Curve order (BN254)
    function q_mod() internal pure returns (uint256) {
        return 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    }

    // Add two G1 points
    function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 6, input, 0x80, r, 0x40)
        }
        require(success, "Pairing addition failed");
    }

    // Multiply a G1 point by a scalar
    function scalar_mul(G1Point memory p, uint s) internal view returns (G1Point memory r) {
        uint[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40)
        }
        require(success, "Pairing scalar_mul failed");
    }

    // Pairing check for two pairs
    function pairing(G1Point[] memory p1, G2Point[] memory p2) internal view returns (bool) {
        require(p1.length == p2.length, "Pairing length mismatch");
        uint elements = p1.length;
        uint inputSize = elements * 6;
        uint[] memory input = new uint[](inputSize);
        for (uint i = 0; i < elements; i++) {
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }
        uint[1] memory out;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
        }
        require(success, "Pairing operation failed");
        return out[0] != 0;
    }

    function pairingProd2(G1Point memory a1, G2Point memory a2, G1Point memory b1, G2Point memory b2)
        internal view returns (bool)
    {
        G1Point ;
        G2Point ;
        p1[0] = a1;
        p1[1] = b1;
        p2[0] = a2;
        p2[1] = b2;
        return pairing(p1, p2);
    }
}

contract Verifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alfa1;
        Pairing.G2Point beta2;
        Pairing.G2Point gamma2;
        Pairing.G2Point delta2;
        Pairing.G1Point[] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    function verifyingKey() internal pure returns (VerifyingKey memory vk) {
        vk.alfa1 = Pairing.G1Point(
            1234567890123456789012345678901234567890123456789012345678901234,
            9876543210987654321098765432109876543210987654321098765432109876
        );

        vk.beta2 = Pairing.G2Point(
            [1111111111111111111111111111111111111111111111111111111111111111,
             2222222222222222222222222222222222222222222222222222222222222222],
            [3333333333333333333333333333333333333333333333333333333333333333,
             4444444444444444444444444444444444444444444444444444444444444444]
        );

        vk.gamma2 = Pairing.P2();
        vk.delta2 = Pairing.P2();

        vk.IC = new Pairing.G1Point ;
        vk.IC[0] = Pairing.G1Point(
            1,
            2
        );
        vk.IC[1] = Pairing.G1Point(
            3,
            4
        );
    }

    function verify(uint[] memory input, Proof memory proof) internal view returns (bool) {
        VerifyingKey memory vk = verifyingKey();
        require(input.length + 1 == vk.IC.length, "Input length mismatch");

        // Compute the linear combination vk_x
        Pairing.G1Point memory vk_x = Pairing.G1Point(0, 0);
        for (uint i = 0; i < input.length; i++) {
            require(input[i] < Pairing.q_mod(), "Input value too large");
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.IC[i + 1], input[i]));
        }
        vk_x = Pairing.addition(vk_x, vk.IC[0]);

        // Check pairing
        if (!Pairing.pairingProd2(
            Pairing.negate(proof.A),
            proof.B,
            Pairing.addition(vk.alfa1, vk_x),
            vk.beta2
        )) return false;

        return true;
    }

    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input
    ) public view returns (bool r) {
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);
        if (verify(input, proof)) {
            return true;
        } else {
            return false;
        }
    }
}